replicaCount: 3

image:
  repository: ghcr.io/distributed-technologies/services-git-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "feature-git-server"

service:
  type: LoadBalancer
  port: 22

affinity: {}

# Create a volume where all trusted public keys are stored in a folder.  
gitServerKeysVolume: {}
# The volume for holding the repos. Required for HA.
gitServerReposVolume: {}
# All git repositories created
repos:
  - services-git-server
  - git-project
