replicaCount: 1

image:
  repository: ghcr.io/distributed-technologies/services-git-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "feature-git-server"

service:
  type: LoadBalancer
  port: 22

affinity: {}

gitServerKeysVolume: {}


