apiVersion: v1
kind: Service
metadata:
  name: git-server-service
spec:
  selector:
    app: git-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: ssh
  type: {{ .Values.service.type }}
