name: Test the setup of git server

on: pull_request

jobs:
  test-git-server-can-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make keys folder
        run: mkdir -p /home/runner/services-git-server/keys 
      
      - name: Make keys
        run: mkdir /home/runner/.ssh -p && ssh-keygen -t rsa -f /home/runner/.ssh/id_rsa 

      - name: Copy public key
        run: cp /home/runner/.ssh/*.pub /home/runner/services-git-server/keys

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with: 
         config: "test/kind.yaml" 
      
      - name: Install dependencies
        run: helm dependency update chart/

      - name: Install LB to expose the Git server 
        run: | 
          helm install --set ipRangeStart=172.18.0.10 \
            --set ipRangeStop=172.18.0.20  \
            --set imagePullPolicy=Always \
            lb https://github.com/distributed-technologies/services-loadbalancer/releases/download/v0.1.3/default.mukube-loadbalancer-v0.1.3.tgz

      - name: Install Git Server
        run: helm install git-server chart/ --values test/values.yaml

      - name: Wait for Git Server
        run: kubectl wait --for=condition=ready pod -l app=git-server --timeout=60s

      - name: Get ip of service
        run: ./wait_for_ip.sh

      - name: Test Git Server
        run: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone ssh://git@172.18.0.10/git-server/repos/services-git-server.git
        